### ISSUE TITLE
Support babel 6

### ISSUE THREAD

**Issue by seawatts** [kellyselden/ember-awesome-macros#282]
After upgrading to ember-cli-babel version 6 I now get an error for [babel-plugin-fake-import-specifiers](https://github.com/kellyselden/babel-plugin-fake-import-specifiers)

```
Error: The (babel-plugin-fake-import-specifiers) Babel 5 plugin is being run with Babel 6.
    at new Plugin (./node_modules/babel-core/lib/api/node.js:110:9)
    at module.exports (./node_modules/babel-plugin-fake-import-specifiers/src/index.js:134:10)
    at Function.memoisePluginContainer (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at ./node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (./node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (./node_modules/babel-core/lib/transformation/file/index.js:212:65)

The broccoli plugin was instantiated at: 
    at Babel.Plugin (./node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (./node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (./node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (./node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Class.transpileTree (./node_modules/ember-cli-babel/index.js:32:48)
    at Object.toTree (./node_modules/ember-cli-babel/index.js:39:30)
    at ./node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (./node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessJs (./node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
```
Looks like https://github.com/kellyselden/babel-plugin-fake-import-specifiers/blob/master/package.json#L26 just needs to be updated.

**Comment by kellyselden** [comment]
It's more difficult than that. Updating to 6 changes the plugin structure and isn't backward compatible. Which means updating makes newer ember-cli work but older start failing. Either a new npm package coded against babel 6 needs to be made and then ember-awesome-macros switches between them, or we need to drop the Math transpiling, or come up with a different strategy. I'm thinking all this babel stuff can go away if we switch to broccoli file generation.

**Comment by seawatts** [comment]
lol shoot... I thought it was going to be a simple upgrade haha, classic! 

Yeah dropping math transpiling doesn't seem like a good way to go. How would the broccoli file generation work?

**Comment by kellyselden** [comment]
We would copy the technique I used [here](https://github.com/kellyselden/ember-a-frame/blob/c01a9c47121e6bebc0b01cd188af56596b2a7544/index.js#L89-L99).
